#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pets
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Pets2")]
	public partial class Pets2BDDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCompra_Medalha(Compra_Medalha instance);
    partial void UpdateCompra_Medalha(Compra_Medalha instance);
    partial void DeleteCompra_Medalha(Compra_Medalha instance);
    partial void InsertDono(Dono instance);
    partial void UpdateDono(Dono instance);
    partial void DeleteDono(Dono instance);
    partial void InsertHtml_Email(Html_Email instance);
    partial void UpdateHtml_Email(Html_Email instance);
    partial void DeleteHtml_Email(Html_Email instance);
    partial void InsertPet(Pet instance);
    partial void UpdatePet(Pet instance);
    partial void DeletePet(Pet instance);
    partial void InsertPets_Desaparecido(Pets_Desaparecido instance);
    partial void UpdatePets_Desaparecido(Pets_Desaparecido instance);
    partial void DeletePets_Desaparecido(Pets_Desaparecido instance);
    partial void InsertPets_Encontrado(Pets_Encontrado instance);
    partial void UpdatePets_Encontrado(Pets_Encontrado instance);
    partial void DeletePets_Encontrado(Pets_Encontrado instance);
    partial void InsertProduto(Produto instance);
    partial void UpdateProduto(Produto instance);
    partial void DeleteProduto(Produto instance);
    #endregion
		
		public Pets2BDDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["Pets2ConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public Pets2BDDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Pets2BDDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Pets2BDDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Pets2BDDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Compra_Medalha> Compra_Medalhas
		{
			get
			{
				return this.GetTable<Compra_Medalha>();
			}
		}
		
		public System.Data.Linq.Table<Dono> Donos
		{
			get
			{
				return this.GetTable<Dono>();
			}
		}
		
		public System.Data.Linq.Table<Html_Email> Html_Emails
		{
			get
			{
				return this.GetTable<Html_Email>();
			}
		}
		
		public System.Data.Linq.Table<Pet> Pets
		{
			get
			{
				return this.GetTable<Pet>();
			}
		}
		
		public System.Data.Linq.Table<Pets_Desaparecido> Pets_Desaparecidos
		{
			get
			{
				return this.GetTable<Pets_Desaparecido>();
			}
		}
		
		public System.Data.Linq.Table<Pets_Encontrado> Pets_Encontrados
		{
			get
			{
				return this.GetTable<Pets_Encontrado>();
			}
		}
		
		public System.Data.Linq.Table<Produto> Produtos
		{
			get
			{
				return this.GetTable<Produto>();
			}
		}
		
		public System.Data.Linq.Table<Racas_Pet> Racas_Pets
		{
			get
			{
				return this.GetTable<Racas_Pet>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Compra_Medalha")]
	public partial class Compra_Medalha : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _produto_id;
		
		private System.Nullable<int> _pet_id;
		
		private string _nome_pet;
		
		private string _telefone_dono;
		
		private float _preco_medalha;
		
		private EntityRef<Pet> _Pet;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onproduto_idChanging(int value);
    partial void Onproduto_idChanged();
    partial void Onpet_idChanging(System.Nullable<int> value);
    partial void Onpet_idChanged();
    partial void Onnome_petChanging(string value);
    partial void Onnome_petChanged();
    partial void Ontelefone_donoChanging(string value);
    partial void Ontelefone_donoChanged();
    partial void Onpreco_medalhaChanging(float value);
    partial void Onpreco_medalhaChanged();
    #endregion
		
		public Compra_Medalha()
		{
			this._Pet = default(EntityRef<Pet>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_produto_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int produto_id
		{
			get
			{
				return this._produto_id;
			}
			set
			{
				if ((this._produto_id != value))
				{
					this.Onproduto_idChanging(value);
					this.SendPropertyChanging();
					this._produto_id = value;
					this.SendPropertyChanged("produto_id");
					this.Onproduto_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pet_id", DbType="Int")]
		public System.Nullable<int> pet_id
		{
			get
			{
				return this._pet_id;
			}
			set
			{
				if ((this._pet_id != value))
				{
					if (this._Pet.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onpet_idChanging(value);
					this.SendPropertyChanging();
					this._pet_id = value;
					this.SendPropertyChanged("pet_id");
					this.Onpet_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nome_pet", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
		public string nome_pet
		{
			get
			{
				return this._nome_pet;
			}
			set
			{
				if ((this._nome_pet != value))
				{
					this.Onnome_petChanging(value);
					this.SendPropertyChanging();
					this._nome_pet = value;
					this.SendPropertyChanged("nome_pet");
					this.Onnome_petChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefone_dono", DbType="NVarChar(12)")]
		public string telefone_dono
		{
			get
			{
				return this._telefone_dono;
			}
			set
			{
				if ((this._telefone_dono != value))
				{
					this.Ontelefone_donoChanging(value);
					this.SendPropertyChanging();
					this._telefone_dono = value;
					this.SendPropertyChanged("telefone_dono");
					this.Ontelefone_donoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_preco_medalha", DbType="Real NOT NULL")]
		public float preco_medalha
		{
			get
			{
				return this._preco_medalha;
			}
			set
			{
				if ((this._preco_medalha != value))
				{
					this.Onpreco_medalhaChanging(value);
					this.SendPropertyChanging();
					this._preco_medalha = value;
					this.SendPropertyChanged("preco_medalha");
					this.Onpreco_medalhaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Pet_Compra_Medalha", Storage="_Pet", ThisKey="pet_id", OtherKey="pet_id", IsForeignKey=true)]
		public Pet Pet
		{
			get
			{
				return this._Pet.Entity;
			}
			set
			{
				Pet previousValue = this._Pet.Entity;
				if (((previousValue != value) 
							|| (this._Pet.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Pet.Entity = null;
						previousValue.Compra_Medalhas.Remove(this);
					}
					this._Pet.Entity = value;
					if ((value != null))
					{
						value.Compra_Medalhas.Add(this);
						this._pet_id = value.pet_id;
					}
					else
					{
						this._pet_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("Pet");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Dono")]
	public partial class Dono : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id_dono;
		
		private string _nome_dono;
		
		private string _sobrenome_dono;
		
		private string _email_dono;
		
		private string _senha_dono;
		
		private System.Data.Linq.Binary _imagem_dono;
		
		private string _endereco_dono;
		
		private string _endereco_lat;
		
		private string _endereco_long;
		
		private string _facebook_dono;
		
		private string _telefone_dono;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_donoChanging(string value);
    partial void Onid_donoChanged();
    partial void Onnome_donoChanging(string value);
    partial void Onnome_donoChanged();
    partial void Onsobrenome_donoChanging(string value);
    partial void Onsobrenome_donoChanged();
    partial void Onemail_donoChanging(string value);
    partial void Onemail_donoChanged();
    partial void Onsenha_donoChanging(string value);
    partial void Onsenha_donoChanged();
    partial void Onimagem_donoChanging(System.Data.Linq.Binary value);
    partial void Onimagem_donoChanged();
    partial void Onendereco_donoChanging(string value);
    partial void Onendereco_donoChanged();
    partial void Onendereco_latChanging(string value);
    partial void Onendereco_latChanged();
    partial void Onendereco_longChanging(string value);
    partial void Onendereco_longChanged();
    partial void Onfacebook_donoChanging(string value);
    partial void Onfacebook_donoChanged();
    partial void Ontelefone_donoChanging(string value);
    partial void Ontelefone_donoChanged();
    #endregion
		
		public Dono()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_dono", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id_dono
		{
			get
			{
				return this._id_dono;
			}
			set
			{
				if ((this._id_dono != value))
				{
					this.Onid_donoChanging(value);
					this.SendPropertyChanging();
					this._id_dono = value;
					this.SendPropertyChanged("id_dono");
					this.Onid_donoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nome_dono", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string nome_dono
		{
			get
			{
				return this._nome_dono;
			}
			set
			{
				if ((this._nome_dono != value))
				{
					this.Onnome_donoChanging(value);
					this.SendPropertyChanging();
					this._nome_dono = value;
					this.SendPropertyChanged("nome_dono");
					this.Onnome_donoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sobrenome_dono", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string sobrenome_dono
		{
			get
			{
				return this._sobrenome_dono;
			}
			set
			{
				if ((this._sobrenome_dono != value))
				{
					this.Onsobrenome_donoChanging(value);
					this.SendPropertyChanging();
					this._sobrenome_dono = value;
					this.SendPropertyChanged("sobrenome_dono");
					this.Onsobrenome_donoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email_dono", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string email_dono
		{
			get
			{
				return this._email_dono;
			}
			set
			{
				if ((this._email_dono != value))
				{
					this.Onemail_donoChanging(value);
					this.SendPropertyChanging();
					this._email_dono = value;
					this.SendPropertyChanged("email_dono");
					this.Onemail_donoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_senha_dono", DbType="NVarChar(80) NOT NULL", CanBeNull=false)]
		public string senha_dono
		{
			get
			{
				return this._senha_dono;
			}
			set
			{
				if ((this._senha_dono != value))
				{
					this.Onsenha_donoChanging(value);
					this.SendPropertyChanging();
					this._senha_dono = value;
					this.SendPropertyChanged("senha_dono");
					this.Onsenha_donoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imagem_dono", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary imagem_dono
		{
			get
			{
				return this._imagem_dono;
			}
			set
			{
				if ((this._imagem_dono != value))
				{
					this.Onimagem_donoChanging(value);
					this.SendPropertyChanging();
					this._imagem_dono = value;
					this.SendPropertyChanged("imagem_dono");
					this.Onimagem_donoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_endereco_dono", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string endereco_dono
		{
			get
			{
				return this._endereco_dono;
			}
			set
			{
				if ((this._endereco_dono != value))
				{
					this.Onendereco_donoChanging(value);
					this.SendPropertyChanging();
					this._endereco_dono = value;
					this.SendPropertyChanged("endereco_dono");
					this.Onendereco_donoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_endereco_lat", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string endereco_lat
		{
			get
			{
				return this._endereco_lat;
			}
			set
			{
				if ((this._endereco_lat != value))
				{
					this.Onendereco_latChanging(value);
					this.SendPropertyChanging();
					this._endereco_lat = value;
					this.SendPropertyChanged("endereco_lat");
					this.Onendereco_latChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_endereco_long", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string endereco_long
		{
			get
			{
				return this._endereco_long;
			}
			set
			{
				if ((this._endereco_long != value))
				{
					this.Onendereco_longChanging(value);
					this.SendPropertyChanging();
					this._endereco_long = value;
					this.SendPropertyChanged("endereco_long");
					this.Onendereco_longChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_facebook_dono", DbType="NVarChar(100)")]
		public string facebook_dono
		{
			get
			{
				return this._facebook_dono;
			}
			set
			{
				if ((this._facebook_dono != value))
				{
					this.Onfacebook_donoChanging(value);
					this.SendPropertyChanging();
					this._facebook_dono = value;
					this.SendPropertyChanged("facebook_dono");
					this.Onfacebook_donoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefone_dono", DbType="NChar(10)")]
		public string telefone_dono
		{
			get
			{
				return this._telefone_dono;
			}
			set
			{
				if ((this._telefone_dono != value))
				{
					this.Ontelefone_donoChanging(value);
					this.SendPropertyChanging();
					this._telefone_dono = value;
					this.SendPropertyChanged("telefone_dono");
					this.Ontelefone_donoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Html_Email")]
	public partial class Html_Email : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _html_email_des;
		
		private string _html_email_senha;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onhtml_email_desChanging(string value);
    partial void Onhtml_email_desChanged();
    partial void Onhtml_email_senhaChanging(string value);
    partial void Onhtml_email_senhaChanged();
    #endregion
		
		public Html_Email()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_html_email_des", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string html_email_des
		{
			get
			{
				return this._html_email_des;
			}
			set
			{
				if ((this._html_email_des != value))
				{
					this.Onhtml_email_desChanging(value);
					this.SendPropertyChanging();
					this._html_email_des = value;
					this.SendPropertyChanged("html_email_des");
					this.Onhtml_email_desChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_html_email_senha", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string html_email_senha
		{
			get
			{
				return this._html_email_senha;
			}
			set
			{
				if ((this._html_email_senha != value))
				{
					this.Onhtml_email_senhaChanging(value);
					this.SendPropertyChanging();
					this._html_email_senha = value;
					this.SendPropertyChanged("html_email_senha");
					this.Onhtml_email_senhaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Pet")]
	public partial class Pet : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _pet_id;
		
		private string _nome_pet;
		
		private string _endereco_dono;
		
		private string _especie_pet;
		
		private string _raca_pet;
		
		private string _sexo_pet;
		
		private string _cor_pet;
		
		private string _dono_pet;
		
		private System.Nullable<int> _status_pet;
		
		private System.Data.Linq.Binary _foto_pet;
		
		private EntitySet<Compra_Medalha> _Compra_Medalhas;
		
		private EntitySet<Pets_Desaparecido> _Pets_Desaparecidos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onpet_idChanging(int value);
    partial void Onpet_idChanged();
    partial void Onnome_petChanging(string value);
    partial void Onnome_petChanged();
    partial void Onendereco_donoChanging(string value);
    partial void Onendereco_donoChanged();
    partial void Onespecie_petChanging(string value);
    partial void Onespecie_petChanged();
    partial void Onraca_petChanging(string value);
    partial void Onraca_petChanged();
    partial void Onsexo_petChanging(string value);
    partial void Onsexo_petChanged();
    partial void Oncor_petChanging(string value);
    partial void Oncor_petChanged();
    partial void Ondono_petChanging(string value);
    partial void Ondono_petChanged();
    partial void Onstatus_petChanging(System.Nullable<int> value);
    partial void Onstatus_petChanged();
    partial void Onfoto_petChanging(System.Data.Linq.Binary value);
    partial void Onfoto_petChanged();
    #endregion
		
		public Pet()
		{
			this._Compra_Medalhas = new EntitySet<Compra_Medalha>(new Action<Compra_Medalha>(this.attach_Compra_Medalhas), new Action<Compra_Medalha>(this.detach_Compra_Medalhas));
			this._Pets_Desaparecidos = new EntitySet<Pets_Desaparecido>(new Action<Pets_Desaparecido>(this.attach_Pets_Desaparecidos), new Action<Pets_Desaparecido>(this.detach_Pets_Desaparecidos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pet_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int pet_id
		{
			get
			{
				return this._pet_id;
			}
			set
			{
				if ((this._pet_id != value))
				{
					this.Onpet_idChanging(value);
					this.SendPropertyChanging();
					this._pet_id = value;
					this.SendPropertyChanged("pet_id");
					this.Onpet_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nome_pet", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string nome_pet
		{
			get
			{
				return this._nome_pet;
			}
			set
			{
				if ((this._nome_pet != value))
				{
					this.Onnome_petChanging(value);
					this.SendPropertyChanging();
					this._nome_pet = value;
					this.SendPropertyChanged("nome_pet");
					this.Onnome_petChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_endereco_dono", DbType="NVarChar(250)")]
		public string endereco_dono
		{
			get
			{
				return this._endereco_dono;
			}
			set
			{
				if ((this._endereco_dono != value))
				{
					this.Onendereco_donoChanging(value);
					this.SendPropertyChanging();
					this._endereco_dono = value;
					this.SendPropertyChanged("endereco_dono");
					this.Onendereco_donoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_especie_pet", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string especie_pet
		{
			get
			{
				return this._especie_pet;
			}
			set
			{
				if ((this._especie_pet != value))
				{
					this.Onespecie_petChanging(value);
					this.SendPropertyChanging();
					this._especie_pet = value;
					this.SendPropertyChanged("especie_pet");
					this.Onespecie_petChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_raca_pet", DbType="NVarChar(20)")]
		public string raca_pet
		{
			get
			{
				return this._raca_pet;
			}
			set
			{
				if ((this._raca_pet != value))
				{
					this.Onraca_petChanging(value);
					this.SendPropertyChanging();
					this._raca_pet = value;
					this.SendPropertyChanged("raca_pet");
					this.Onraca_petChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sexo_pet", DbType="NVarChar(6)")]
		public string sexo_pet
		{
			get
			{
				return this._sexo_pet;
			}
			set
			{
				if ((this._sexo_pet != value))
				{
					this.Onsexo_petChanging(value);
					this.SendPropertyChanging();
					this._sexo_pet = value;
					this.SendPropertyChanged("sexo_pet");
					this.Onsexo_petChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cor_pet", DbType="NVarChar(15)")]
		public string cor_pet
		{
			get
			{
				return this._cor_pet;
			}
			set
			{
				if ((this._cor_pet != value))
				{
					this.Oncor_petChanging(value);
					this.SendPropertyChanging();
					this._cor_pet = value;
					this.SendPropertyChanged("cor_pet");
					this.Oncor_petChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dono_pet", DbType="NVarChar(100)")]
		public string dono_pet
		{
			get
			{
				return this._dono_pet;
			}
			set
			{
				if ((this._dono_pet != value))
				{
					this.Ondono_petChanging(value);
					this.SendPropertyChanging();
					this._dono_pet = value;
					this.SendPropertyChanged("dono_pet");
					this.Ondono_petChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status_pet", DbType="Int")]
		public System.Nullable<int> status_pet
		{
			get
			{
				return this._status_pet;
			}
			set
			{
				if ((this._status_pet != value))
				{
					this.Onstatus_petChanging(value);
					this.SendPropertyChanging();
					this._status_pet = value;
					this.SendPropertyChanged("status_pet");
					this.Onstatus_petChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_foto_pet", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary foto_pet
		{
			get
			{
				return this._foto_pet;
			}
			set
			{
				if ((this._foto_pet != value))
				{
					this.Onfoto_petChanging(value);
					this.SendPropertyChanging();
					this._foto_pet = value;
					this.SendPropertyChanged("foto_pet");
					this.Onfoto_petChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Pet_Compra_Medalha", Storage="_Compra_Medalhas", ThisKey="pet_id", OtherKey="pet_id")]
		public EntitySet<Compra_Medalha> Compra_Medalhas
		{
			get
			{
				return this._Compra_Medalhas;
			}
			set
			{
				this._Compra_Medalhas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Pet_Pets_Desaparecido", Storage="_Pets_Desaparecidos", ThisKey="pet_id", OtherKey="pet_id")]
		public EntitySet<Pets_Desaparecido> Pets_Desaparecidos
		{
			get
			{
				return this._Pets_Desaparecidos;
			}
			set
			{
				this._Pets_Desaparecidos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Compra_Medalhas(Compra_Medalha entity)
		{
			this.SendPropertyChanging();
			entity.Pet = this;
		}
		
		private void detach_Compra_Medalhas(Compra_Medalha entity)
		{
			this.SendPropertyChanging();
			entity.Pet = null;
		}
		
		private void attach_Pets_Desaparecidos(Pets_Desaparecido entity)
		{
			this.SendPropertyChanging();
			entity.Pet = this;
		}
		
		private void detach_Pets_Desaparecidos(Pets_Desaparecido entity)
		{
			this.SendPropertyChanging();
			entity.Pet = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Pets_Desaparecidos")]
	public partial class Pets_Desaparecido : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_desaparecimento;
		
		private int _pet_id;
		
		private string _nome_pet;
		
		private string _especie_pet;
		
		private string _raca_pet;
		
		private string _sexo_pet;
		
		private string _cor_pet;
		
		private string _dono_pet;
		
		private string _telefone_dono;
		
		private string _facebook_dono;
		
		private string _endereco;
		
		private string _endereco_loca_lat;
		
		private string _endereco_loca_lng;
		
		private string _data_des;
		
		private string _hora_des;
		
		private EntityRef<Pet> _Pet;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_desaparecimentoChanging(int value);
    partial void Onid_desaparecimentoChanged();
    partial void Onpet_idChanging(int value);
    partial void Onpet_idChanged();
    partial void Onnome_petChanging(string value);
    partial void Onnome_petChanged();
    partial void Onespecie_petChanging(string value);
    partial void Onespecie_petChanged();
    partial void Onraca_petChanging(string value);
    partial void Onraca_petChanged();
    partial void Onsexo_petChanging(string value);
    partial void Onsexo_petChanged();
    partial void Oncor_petChanging(string value);
    partial void Oncor_petChanged();
    partial void Ondono_petChanging(string value);
    partial void Ondono_petChanged();
    partial void Ontelefone_donoChanging(string value);
    partial void Ontelefone_donoChanged();
    partial void Onfacebook_donoChanging(string value);
    partial void Onfacebook_donoChanged();
    partial void OnenderecoChanging(string value);
    partial void OnenderecoChanged();
    partial void Onendereco_loca_latChanging(string value);
    partial void Onendereco_loca_latChanged();
    partial void Onendereco_loca_lngChanging(string value);
    partial void Onendereco_loca_lngChanged();
    partial void Ondata_desChanging(string value);
    partial void Ondata_desChanged();
    partial void Onhora_desChanging(string value);
    partial void Onhora_desChanged();
    #endregion
		
		public Pets_Desaparecido()
		{
			this._Pet = default(EntityRef<Pet>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_desaparecimento", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_desaparecimento
		{
			get
			{
				return this._id_desaparecimento;
			}
			set
			{
				if ((this._id_desaparecimento != value))
				{
					this.Onid_desaparecimentoChanging(value);
					this.SendPropertyChanging();
					this._id_desaparecimento = value;
					this.SendPropertyChanged("id_desaparecimento");
					this.Onid_desaparecimentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pet_id", DbType="Int NOT NULL")]
		public int pet_id
		{
			get
			{
				return this._pet_id;
			}
			set
			{
				if ((this._pet_id != value))
				{
					if (this._Pet.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onpet_idChanging(value);
					this.SendPropertyChanging();
					this._pet_id = value;
					this.SendPropertyChanged("pet_id");
					this.Onpet_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nome_pet", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string nome_pet
		{
			get
			{
				return this._nome_pet;
			}
			set
			{
				if ((this._nome_pet != value))
				{
					this.Onnome_petChanging(value);
					this.SendPropertyChanging();
					this._nome_pet = value;
					this.SendPropertyChanged("nome_pet");
					this.Onnome_petChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_especie_pet", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string especie_pet
		{
			get
			{
				return this._especie_pet;
			}
			set
			{
				if ((this._especie_pet != value))
				{
					this.Onespecie_petChanging(value);
					this.SendPropertyChanging();
					this._especie_pet = value;
					this.SendPropertyChanged("especie_pet");
					this.Onespecie_petChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_raca_pet", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
		public string raca_pet
		{
			get
			{
				return this._raca_pet;
			}
			set
			{
				if ((this._raca_pet != value))
				{
					this.Onraca_petChanging(value);
					this.SendPropertyChanging();
					this._raca_pet = value;
					this.SendPropertyChanged("raca_pet");
					this.Onraca_petChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sexo_pet", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string sexo_pet
		{
			get
			{
				return this._sexo_pet;
			}
			set
			{
				if ((this._sexo_pet != value))
				{
					this.Onsexo_petChanging(value);
					this.SendPropertyChanging();
					this._sexo_pet = value;
					this.SendPropertyChanged("sexo_pet");
					this.Onsexo_petChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cor_pet", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string cor_pet
		{
			get
			{
				return this._cor_pet;
			}
			set
			{
				if ((this._cor_pet != value))
				{
					this.Oncor_petChanging(value);
					this.SendPropertyChanging();
					this._cor_pet = value;
					this.SendPropertyChanged("cor_pet");
					this.Oncor_petChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dono_pet", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string dono_pet
		{
			get
			{
				return this._dono_pet;
			}
			set
			{
				if ((this._dono_pet != value))
				{
					this.Ondono_petChanging(value);
					this.SendPropertyChanging();
					this._dono_pet = value;
					this.SendPropertyChanged("dono_pet");
					this.Ondono_petChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefone_dono", DbType="NVarChar(10)")]
		public string telefone_dono
		{
			get
			{
				return this._telefone_dono;
			}
			set
			{
				if ((this._telefone_dono != value))
				{
					this.Ontelefone_donoChanging(value);
					this.SendPropertyChanging();
					this._telefone_dono = value;
					this.SendPropertyChanged("telefone_dono");
					this.Ontelefone_donoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_facebook_dono", DbType="NVarChar(100)")]
		public string facebook_dono
		{
			get
			{
				return this._facebook_dono;
			}
			set
			{
				if ((this._facebook_dono != value))
				{
					this.Onfacebook_donoChanging(value);
					this.SendPropertyChanging();
					this._facebook_dono = value;
					this.SendPropertyChanged("facebook_dono");
					this.Onfacebook_donoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_endereco", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string endereco
		{
			get
			{
				return this._endereco;
			}
			set
			{
				if ((this._endereco != value))
				{
					this.OnenderecoChanging(value);
					this.SendPropertyChanging();
					this._endereco = value;
					this.SendPropertyChanged("endereco");
					this.OnenderecoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_endereco_loca_lat", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string endereco_loca_lat
		{
			get
			{
				return this._endereco_loca_lat;
			}
			set
			{
				if ((this._endereco_loca_lat != value))
				{
					this.Onendereco_loca_latChanging(value);
					this.SendPropertyChanging();
					this._endereco_loca_lat = value;
					this.SendPropertyChanged("endereco_loca_lat");
					this.Onendereco_loca_latChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_endereco_loca_lng", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string endereco_loca_lng
		{
			get
			{
				return this._endereco_loca_lng;
			}
			set
			{
				if ((this._endereco_loca_lng != value))
				{
					this.Onendereco_loca_lngChanging(value);
					this.SendPropertyChanging();
					this._endereco_loca_lng = value;
					this.SendPropertyChanged("endereco_loca_lng");
					this.Onendereco_loca_lngChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data_des", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string data_des
		{
			get
			{
				return this._data_des;
			}
			set
			{
				if ((this._data_des != value))
				{
					this.Ondata_desChanging(value);
					this.SendPropertyChanging();
					this._data_des = value;
					this.SendPropertyChanged("data_des");
					this.Ondata_desChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hora_des", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string hora_des
		{
			get
			{
				return this._hora_des;
			}
			set
			{
				if ((this._hora_des != value))
				{
					this.Onhora_desChanging(value);
					this.SendPropertyChanging();
					this._hora_des = value;
					this.SendPropertyChanged("hora_des");
					this.Onhora_desChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Pet_Pets_Desaparecido", Storage="_Pet", ThisKey="pet_id", OtherKey="pet_id", IsForeignKey=true)]
		public Pet Pet
		{
			get
			{
				return this._Pet.Entity;
			}
			set
			{
				Pet previousValue = this._Pet.Entity;
				if (((previousValue != value) 
							|| (this._Pet.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Pet.Entity = null;
						previousValue.Pets_Desaparecidos.Remove(this);
					}
					this._Pet.Entity = value;
					if ((value != null))
					{
						value.Pets_Desaparecidos.Add(this);
						this._pet_id = value.pet_id;
					}
					else
					{
						this._pet_id = default(int);
					}
					this.SendPropertyChanged("Pet");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Pets_Encontrados")]
	public partial class Pets_Encontrado : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_encontro;
		
		private int _pet_id;
		
		private string _nome_pet;
		
		private string _dono_pet;
		
		private string _especie_pet;
		
		private string _raca_pet;
		
		private string _sexo_pet;
		
		private string _data_enc;
		
		private string _hora_enc;
		
		private string _data_des;
		
		private string _hora_des;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_encontroChanging(int value);
    partial void Onid_encontroChanged();
    partial void Onpet_idChanging(int value);
    partial void Onpet_idChanged();
    partial void Onnome_petChanging(string value);
    partial void Onnome_petChanged();
    partial void Ondono_petChanging(string value);
    partial void Ondono_petChanged();
    partial void Onespecie_petChanging(string value);
    partial void Onespecie_petChanged();
    partial void Onraca_petChanging(string value);
    partial void Onraca_petChanged();
    partial void Onsexo_petChanging(string value);
    partial void Onsexo_petChanged();
    partial void Ondata_encChanging(string value);
    partial void Ondata_encChanged();
    partial void Onhora_encChanging(string value);
    partial void Onhora_encChanged();
    partial void Ondata_desChanging(string value);
    partial void Ondata_desChanged();
    partial void Onhora_desChanging(string value);
    partial void Onhora_desChanged();
    #endregion
		
		public Pets_Encontrado()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_encontro", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_encontro
		{
			get
			{
				return this._id_encontro;
			}
			set
			{
				if ((this._id_encontro != value))
				{
					this.Onid_encontroChanging(value);
					this.SendPropertyChanging();
					this._id_encontro = value;
					this.SendPropertyChanged("id_encontro");
					this.Onid_encontroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pet_id", DbType="Int NOT NULL")]
		public int pet_id
		{
			get
			{
				return this._pet_id;
			}
			set
			{
				if ((this._pet_id != value))
				{
					this.Onpet_idChanging(value);
					this.SendPropertyChanging();
					this._pet_id = value;
					this.SendPropertyChanged("pet_id");
					this.Onpet_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nome_pet", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string nome_pet
		{
			get
			{
				return this._nome_pet;
			}
			set
			{
				if ((this._nome_pet != value))
				{
					this.Onnome_petChanging(value);
					this.SendPropertyChanging();
					this._nome_pet = value;
					this.SendPropertyChanged("nome_pet");
					this.Onnome_petChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dono_pet", DbType="NVarChar(100)")]
		public string dono_pet
		{
			get
			{
				return this._dono_pet;
			}
			set
			{
				if ((this._dono_pet != value))
				{
					this.Ondono_petChanging(value);
					this.SendPropertyChanging();
					this._dono_pet = value;
					this.SendPropertyChanged("dono_pet");
					this.Ondono_petChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_especie_pet", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string especie_pet
		{
			get
			{
				return this._especie_pet;
			}
			set
			{
				if ((this._especie_pet != value))
				{
					this.Onespecie_petChanging(value);
					this.SendPropertyChanging();
					this._especie_pet = value;
					this.SendPropertyChanged("especie_pet");
					this.Onespecie_petChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_raca_pet", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string raca_pet
		{
			get
			{
				return this._raca_pet;
			}
			set
			{
				if ((this._raca_pet != value))
				{
					this.Onraca_petChanging(value);
					this.SendPropertyChanging();
					this._raca_pet = value;
					this.SendPropertyChanged("raca_pet");
					this.Onraca_petChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sexo_pet", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string sexo_pet
		{
			get
			{
				return this._sexo_pet;
			}
			set
			{
				if ((this._sexo_pet != value))
				{
					this.Onsexo_petChanging(value);
					this.SendPropertyChanging();
					this._sexo_pet = value;
					this.SendPropertyChanged("sexo_pet");
					this.Onsexo_petChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data_enc", DbType="NVarChar(10)")]
		public string data_enc
		{
			get
			{
				return this._data_enc;
			}
			set
			{
				if ((this._data_enc != value))
				{
					this.Ondata_encChanging(value);
					this.SendPropertyChanging();
					this._data_enc = value;
					this.SendPropertyChanged("data_enc");
					this.Ondata_encChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hora_enc", DbType="NVarChar(10)")]
		public string hora_enc
		{
			get
			{
				return this._hora_enc;
			}
			set
			{
				if ((this._hora_enc != value))
				{
					this.Onhora_encChanging(value);
					this.SendPropertyChanging();
					this._hora_enc = value;
					this.SendPropertyChanged("hora_enc");
					this.Onhora_encChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data_des", DbType="NVarChar(10)")]
		public string data_des
		{
			get
			{
				return this._data_des;
			}
			set
			{
				if ((this._data_des != value))
				{
					this.Ondata_desChanging(value);
					this.SendPropertyChanging();
					this._data_des = value;
					this.SendPropertyChanged("data_des");
					this.Ondata_desChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hora_des", DbType="NVarChar(10)")]
		public string hora_des
		{
			get
			{
				return this._hora_des;
			}
			set
			{
				if ((this._hora_des != value))
				{
					this.Onhora_desChanging(value);
					this.SendPropertyChanging();
					this._hora_des = value;
					this.SendPropertyChanged("hora_des");
					this.Onhora_desChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Produto")]
	public partial class Produto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _produto_id;
		
		private string _nome_produto;
		
		private string _descricao_produto;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onproduto_idChanging(int value);
    partial void Onproduto_idChanged();
    partial void Onnome_produtoChanging(string value);
    partial void Onnome_produtoChanged();
    partial void Ondescricao_produtoChanging(string value);
    partial void Ondescricao_produtoChanged();
    #endregion
		
		public Produto()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_produto_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int produto_id
		{
			get
			{
				return this._produto_id;
			}
			set
			{
				if ((this._produto_id != value))
				{
					this.Onproduto_idChanging(value);
					this.SendPropertyChanging();
					this._produto_id = value;
					this.SendPropertyChanged("produto_id");
					this.Onproduto_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nome_produto", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string nome_produto
		{
			get
			{
				return this._nome_produto;
			}
			set
			{
				if ((this._nome_produto != value))
				{
					this.Onnome_produtoChanging(value);
					this.SendPropertyChanging();
					this._nome_produto = value;
					this.SendPropertyChanged("nome_produto");
					this.Onnome_produtoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descricao_produto", DbType="NVarChar(200)")]
		public string descricao_produto
		{
			get
			{
				return this._descricao_produto;
			}
			set
			{
				if ((this._descricao_produto != value))
				{
					this.Ondescricao_produtoChanging(value);
					this.SendPropertyChanging();
					this._descricao_produto = value;
					this.SendPropertyChanged("descricao_produto");
					this.Ondescricao_produtoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Racas_Pets")]
	public partial class Racas_Pet
	{
		
		private string _pets_cachorro;
		
		private string _pets_gato;
		
		public Racas_Pet()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pets_cachorro", DbType="NVarChar(40)")]
		public string pets_cachorro
		{
			get
			{
				return this._pets_cachorro;
			}
			set
			{
				if ((this._pets_cachorro != value))
				{
					this._pets_cachorro = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pets_gato", DbType="NVarChar(40)")]
		public string pets_gato
		{
			get
			{
				return this._pets_gato;
			}
			set
			{
				if ((this._pets_gato != value))
				{
					this._pets_gato = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
